version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/src

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   command: bash -c "cd /src/app && yarn install && yarn start"
  #   volumes:
  #   - ${ADBREW_CODEBASE_PATH}:/src
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #   - api

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src
    environment:
      - CHOKIDAR_USEPOLLING=true

  # mongo:
  #   build: .
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ${ADBREW_CODEBASE_PATH}/db/:/data/db
  #   command: /usr/bin/mongod --bind_ip 0.0.0.0

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data:

